# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python
name: Test Python 🐍 package

on:
    push:
      branches: [main, dev]
      paths-ignore:
        - "**.md"
        - "**.bib"
        - "**.ya?ml"
        - "LICENSE"
        - ".gitignore"
        - "**.ipynb"
    pull_request:
        branches: [main, dev]
        types: [opened, reopened]
        paths-ignore:
            - "**.md"
            - "**.bib"
            - "**.ya?ml"
            - "LICENSE"
            - ".gitignore"
            - "**.ipynb"
    workflow_dispatch:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12", "3.13"]

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Display Python version
              run: python -c "import sys; print(sys.version)"
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install .[test]
            - name: Test with pytest
              run: |
                    pip install pytest pytest-cov
                    pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html